---
- name: Deploying the PHP Applicaion to Dev Enviroment
  become: true
  hosts: todo

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - dirmngr
          - gnupg
          - software-properties-common
        state: present

    - name: Add PHP repository
      ansible.builtin.apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: install Apache on the webserver
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: ensure httpd is started and enabled
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes

    - name: Install PHP and required extensions
      ansible.builtin.apt:
        name:
          - php
          - php-mysql
          - php-gd
          - php-curl
          - unzip
          - php-common
          - php-mbstring
          #- php-opcache
          - php-intl
          - php-xml
          - php-fpm
          - php-json
        state: present

    #- name: Ensure PHP-FPM is started and enabled
    #  ansible.builtin.service:
    #    name: php-fpm
    #    state: started
    #    enabled: yes

    - name: Ensure source directory exists
      ansible.builtin.file:
        path: /home/ubuntu/var/lib/jenkins/workspace/php_todo_cicd/
        state: directory

    - name: Download the artifact
      ansible.builtin.get_url:
        url: http://18.134.137.130:8082/artifactory/PBL/php-todo.zip
        dest: /home/ubuntu/var/lib/jenkins/workspace/php_todo_cicd/
        url_username: admin
        url_password: iamYole86

    - name: unzip the artifacts
      ansible.builtin.unarchive:
        src: /home/ubuntu/var/lib/jenkins/workspace/php_todo_cicd/php-todo.zip
        dest: /home/ubuntu/var/lib/jenkins/workspace/php_todo_cicd/
        remote_src: yes

    - name: deploy the code
      ansible.builtin.copy:
        src: /home/ubuntu/var/lib/jenkins/workspace/php_todo_cicd/
        dest: /var/www/html/
        remote_src: yes

    - name: Remove Apache default page
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

    - name: Restart Apache
      ansible.builtin.service:
        name: apache2
        state: restarted
