all:
  vars:
    ansible_ssh_private_key_file: /home/keys/dio_key.pem

  hosts:
    jenkins:
      ansible_host: 172.31.36.144
      ansible_user: ubuntu
    nginx:
      ansible_host: 172.31.47.1
      ansible_user: ubuntu
    artifact_repository:
      ansible_host: 172.31.34.118
      ansible_user: ubuntu
    sonarqube:
      ansible_host: 172.31.10.101
      ansible_user: ubuntu

  children:
    ci_env_all:
      hosts:
        jenkins:
        nginx:
        artifact_repository:
        sonarqube:
