all:
  hosts:
    tooling:
      ansible_host: 172.31.41.31
      ansible_user: ubuntu
    todo:
      ansible_host: 172.31.47.126
      ansible_user: ubuntu
    nginx:
      ansible_host: 172.31.33.204
      ansible_user: ubuntu
    db:
      ansible_host: 172.31.42.200
      ansible_user: ec2-user
      ansible_python_interpreter: /usr/bin/python

  children:
    webservers:
      hosts:
        tooling:
        todo:
