all:
  vars:
    ansible_ssh_private_key_file: /home/keys/dio_key.pem

  hosts:
    webserver_1:
      ansible_host: 172.31.40.150
      ansible_user: ec2-user
    webserver_2:
      ansible_host: 172.31.37.142
      ansible_user: ec2-user
    webserver_3:
      ansible_host: 172.31.40.123
      ansible_user: ec2-user
    db:
      ansible_host: 172.31.43.28
      ansible_user: ubuntu
    nfs:
      ansible_host: 172.31.47.126
      ansible_user: ec2-user

  children:
    webservers:
      hosts:
        webserver_1:
        webserver_2:
        webserver_3:
    dbservers:
      hosts:
        db
    nfsserver:
      hosts:
        nfs
    org:
      children:
        nfsserver:
        dbservers:
        webservers:
