all:
  vars:
    ansible_ssh_private_key_file: /home/keys/dio_key.pem

  hosts:
    tooling:
      ansible_host: 172.31.40.150
      ansible_user: ubuntu
    todo:
      ansible_host: 172.31.37.142
      ansible_user: ubuntu
    nginx:
      ansible_host: 172.31.40.123
      ansible_user: ubuntu
    db:
      ansible_host: 172.31.42.200
      ansible_user: ec2-user
      ansible_python_interpreter: /usr/bin/python

  children:
    webservers:
      hosts:
        tooling:
        todo:
