---
- name: install apache
  become: true
  ansible.builtin.apt:
    name: "apache2"
    state: present

- name: install git
  become: true
  ansible.builtin.apt:
    name: "git"
    state: present

- name: Start service httpd, if not started
  become: true
  ansible.builtin.service:
    name: apache2
    state: started
