---
- hosts: all
- name: Include dynamic variables
  import_playbook: ../static-assignments/common.yml
  include: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- hosts: dev-webservers
- name: Provisioning the Dev_Env Webservers
  import_playbook: ../static-assignments/devwebservers.yml
