---
- hosts: all
  name: Include dynamic variables
  tasks:
    - include: ../static-assignments/common.yml
    - include_vars: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- hosts: database_servers
  name: Configuring UAT Database Servers
  tasks:
    - include: ../static-assignments/uatdbserver.yml

- hosts: uat-webservers
  name: Configuring UAT Web Servers
  tasks:
    - include: ../static-assignments/uatwebservers.yml

- hosts: loadbalancer_servers
  name: Configuring and Enabling Load Balancer
  tasks:
    - include: ../static-assignments/uatloadbalancer.yml
      when: load_balancer_is_required
