---
#- hosts: all
#- import_playbook: ../static-assignments/common.yml

- hosts: uat-webservers
- name: Configuring UAT Web Servers
- import_playbook: ../static-assignments/uatwebservers.yml

- hosts: database_servers
- name: Configuring UAT Database Servers
- import_playbook: ../static-assignments/uatdbserver.yml

- name: Loadbalancers assignment
  hosts: loadbalancer_servers
    - import_playbook: ../static-assignments/uatloadbalancers.yml
  when: load_balancer_is_required
