---
- hosts: all
- name: Include dynamic variables
  tasks:
  import_playbook: ../static-assignments/common.yml
  include: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- hosts: webservers
- name: Webserver assignment
  import_playbook: ../static-assignments/uatwebservers.yml
#- hosts: loadbalancer_servers
#- name: Configuring the Load Balancers
#  import_playbook: ../static-assignments/uatloadbalancer.yml
#  when: load_balancer_is_required
